### ISSUE TITLE
Creating Delivery Channel failed: MaxNumberOfDeliveryChannelsExceededException

### ISSUE THREAD

**Issue by metegenez** [trussworks/terraform-aws-config#121]
Hi,
I used AWS Config before, so Delivery Channel and Recorder is already exists. How can I make a modification on existing stuff? (Not built with Terraform.)

**Comment by dynamike** [comment]
Yeah, you can just set `enable_config_recorder` to false in that case

**Comment by metegenez** [comment]
Yeah I found that after I opened this issue. Thanks.
