### ISSUE TITLE
Disable the module based on condition

### ISSUE THREAD

**Issue by tirth-unix** [trussworks/terraform-aws-config#136]
* I need to set the condition for enabling or disabling the module based on a certain value. For example, if I use the count, the rules are destroyed and recreated on every terraform run. Can we add some variable "enabled" to the module to make life easy?

**Comment by avanti-joshi** [comment]
@tirth-unix apologies for the delay! Was curious if there would be an issue with just commenting out the module code and destroying/recreating the resources as needed.

**Comment by rpdelaney** [comment]
Closing as stale
