### ISSUE TITLE
Creating Configuration Recorder failed: MaxNumberOfConfigurationRecordersExceededException 

### ISSUE THREAD

**Issue by marekpawlowski** [trussworks/terraform-aws-config#69]
I have problem with module i get that error message:

`Error: Creating Configuration Recorder failed: MaxNumberOfConfigurationRecordersExceededException: Failed to put configuration recorder 'test' because the maximum number of configuration recorders: 1 is reached.

  on .terraform/modules/config/terraform-aws-config-2.5.4/config-service.tf line 24, in resource "aws_config_configuration_recorder" "main":
  24: resource "aws_config_configuration_recorder" "main" {`

i base configuration:

`module "config" {
  source  = "trussworks/config/aws"
  version = "2.5.4"
 
  config_name        = "test"
  config_logs_bucket = "test"

}`

`provider "aws" {
  region     = "eu-central-1"
  version = "~> 2.53.0"
}

terraform {
  required_version = "~> 0.12.18"
}`

**Comment by dynamike** [comment]
This error is due to you already having a running instance of AWS config in `eu-central-1`. AWS has a hard cap of 1 config recorder instance per region. So you'll either need to delete the running AWS config instance or tell terraform to setup an instance in another region.

**Comment by marekpawlowski** [comment]
True story bro.... thanks for info it is working now :)
