### ISSUE TITLE
AWSConfigRole policy being deprecated

### ISSUE THREAD

**Issue by davidski** [trussworks/terraform-aws-config#85]
The AWS Managed AWSConfigRole policy is being deprecated, with AWS mailing out advisories to accounts that are using this policy.

This policy is currently applied via https://github.com/trussworks/terraform-aws-config/blob/09a8e0e2e37e47056e6f18d0c1a7152f482dbdbf/iam.tf#L75-L78. AWS's recommendation is to instead use the new AWS_ConfigRole managed policy, which has tighter permissions than the old AWSConfigRole policy.

This looks like it may be low impact update. Thanks for the module!

**Comment by eeeady** [comment]
On it!

**Comment by eeeady** [comment]
Looks good to go! Use anything after v4.0.1.
