### ISSUE TITLE
Create custom rules

### ISSUE THREAD

**Issue by tomasbackman** [trussworks/terraform-aws-config#88]
Is it possible to use this module to create custom config rules as well?

Or is it just for configuring the included rules? 
And what are the rules based on? Do they correspond to the default AWS managed rules or something else?

**Comment by eeeady** [comment]
Hi @tomasbackman! 

This module is designed to configure basic AWS managed rules that we generally suggest and use in our AWS accounts. This module is not set up to create or incorporate custom config rules.

I haven't personally created any custom config rules but if I were to, I would stand up an aws account and use this module to configure some base config rules and listeners then use the [AWS Provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule) to either create rules for my account or if I knew I was going to reuse them create my own module in my TF repo.

**Comment by tomasbackman** [comment]
Thanks for the answer. I will probably do as you suggest and try to use this module as the base to setup config and base rules. And when/if we want some custom rules I will implement them by myself with terraform.
