### ISSUE TITLE
Loosen version constraint to permit terraform 0.14

### ISSUE THREAD

**Issue by davidski** [trussworks/terraform-aws-config#99]
Terraform 0.14 is now GA and being pushed via homebrew. Could this module's terraform version constrained to loosened? It currently specifies `< 0.14`.

Thanks for the work maintaining this module!

**Comment by dynamike** [comment]
Good suggestion, I do think we are a bit constrictive on the versions in general . Feel free to pop a PR to relax the constraints if you need this sooner rather than later. We'll likely be rolling this out in the coming week if we don't hear from you.

**Comment by davidski** [comment]
Hi, @dynamike - I've got a PR open over at lucky #100. Any chance you could review and, if acceptable, merge this in? This is one of the few blockers I have left for a tf 0.14 upgrade project. Thanks a bunch!

**Comment by dynamike** [comment]
Yeah, I've got a branch based on your changes over at https://github.com/trussworks/terraform-aws-config/tree/mk-terraform014 that I plan to wrap up as a PR on Monday
